server:
  port: 8002
spring:
  application:
    name: consumer-service
    
dubbo:
  application:
    name: consumer-service
  registry:
    address: zookeeper://q-host:2181
  protocol:
    name: dubbo
  consumer:
    check: true