server:
  port: 8002
spring:
  application:
    name: consumer-service
    
#grpc:
#  client:
#    port: 9090


# grpc配置
grpc:
  # grpc clienT相关配置
  client:
    # 服务名（不同服务名可对应不同配置）
    # nacos-grpc是服务端配置的名字，GrpcClient注解会用到
    demo-grpc:
#      gRPC服务端地址
#      address: 'dns://127.0.0.1:19898'
      address: 'static://127.0.0.1:9090'
      # 是否开启保持连接（长连接）
      enableKeepAlive: true
      # 保持连接时长（默认20s）
      keepAliveTimeout: 20s
      # 没有RPC调用时是否保持连接（默认false，可禁用避免额外消耗CPU）
      keepAliveWithoutCalls: false
      # 客户端负载均衡策略(round_robin（默认）, pick_first)
      defaultLoadBalancingPolicy: round_robin
      # 通信类型
      # plaintext | plaintext_upgrade | tls
      # 明文通信且http/2 | 明文通信且升级http/1.1为http/2 | 使用TLS（ALPN/NPN）通信
      negotiationType: plaintext