server:
  port: 40911
spring:
  datasource:
    url: jdbc:h2:/temp/h2-db/h2-demo
    driver-class-name: org.h2.Driver
    username: root  
    password: 123456
  h2:
    console:
      path: /h2-console
      enabled: true