server:
  port: 8001
spring:
  application:
    name: dubbo-provider-service
    
    
dubbo:
  application:
    name: dubbo-provider-service
  registry:
    address: zookeeper://q-host:2181
  protocol:
    name: dubbo
    port: 20880
  scan:
    #重要配置，等待分析
    base-packages: com.github.xhrg